# coding=utf-8
import jieba
import matplotlib.pyplot as plt
from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator
summarys=[]
with open('BGM_result.csv', mode='r', encoding='utf-8') as f:
    rows = f.readlines()
    for row in rows:
        summary = row.split(',')
        if summarys != '':
            summarys.append(summary)

comment_after_split = jieba.cut_for_search(str(summarys))
words = " ".join(comment_after_split)  # 以空格进行拼接

stopwords = STOPWORDS.copy()
stopwords.add("<p>")
stopwords.add("</p>")
stopwords.add("游戏")
stopwords.add("这个")
stopwords.add("不是")
stopwords.add("一部")
stopwords.add("一个")
stopwords.add("没有")
stopwords.add("什么")
stopwords.add("有点")
stopwords.add("现在")
stopwords.add("还是")
stopwords.add("但是")
stopwords.add("有点")
stopwords.add("然后")
stopwords.add("还有")
stopwords.add("而且")
stopwords.add("不过")
stopwords.add("虽然")
stopwords.add("因为")
stopwords.add("所以")
stopwords.add("如果")
stopwords.add("自己")
stopwords.add("他们")
stopwords.add("u3000")
stopwords.add("评分")
stopwords.add("然而")
stopwords.add("发生")
stopwords.add("xa0")
stopwords.add("第二")
stopwords.add("二季")
stopwords.add("发生")
stopwords.add("拥有")
stopwords.add("单行")
stopwords.add("开始")
stopwords.add("一起")
stopwords.add("OVA")
stopwords.add("之间")
stopwords.add("角色")
stopwords.add("之后")
stopwords.add("以及")
stopwords.add("主人")
stopwords.add("已经")
stopwords.add("为了")
stopwords.add("成为")
stopwords.add("存在")
stopwords.add("故事")
stopwords.add("出现")
stopwords.add("巨大")
stopwords.add("动画")
stopwords.add("她们")
stopwords.add("中生")
stopwords.add("制作")
stopwords.add("由于")
stopwords.add("这样")
stopwords.add("作为")
stopwords.add("剧场")
stopwords.add("剧场版")
stopwords.add("突然")
stopwords.add("二季")
stopwords.add("可是")
stopwords.add("完成")
stopwords.add("主角")
stopwords.add("有这")
stopwords.add("内容")
stopwords.add("同时")
stopwords.add("进行")
stopwords.add("所以")
stopwords.add("原作")
stopwords.add("两人")



bg_image = plt.imread('123.jpg')

wc = WordCloud(width=1024, height=768, background_color='white', mask=bg_image, font_path='STKAITI.TTF',stopwords=stopwords, max_font_size=300, random_state=50)
wc.generate_from_text(words)
plt.imshow(wc)
plt.axis('off')  # 不显示坐标轴
plt.show()
# 保存结果到本地

wc.to_file('词云图.jpg')
